version: "2"
services:
  server:
    image: registry:2
    network_mode: host
    volumes:
      - storage:/var/lib/registry
    ports:
      - 5000:5000
    restart: unless-stopped

volumes:
  storage: {}
