- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: create workspace
      file:
        dest: /home/vagrant/potatobox/roles/alluxio-job-master
        state: directory
        owner: vagrant
        group: vagrant

    - name: copy docker-compose.yaml
      copy:
        src: docker-compose.yaml
        dest: /home/vagrant/potatobox/roles/alluxio-job-master
        owner: vagrant
        group: vagrant

    - name: put .env
      copy:
        content: |
          IMAGE_PREFIX={{ image_prefix }}
          IMAGE_TAG={{ image_tag }}
        dest: /home/vagrant/potatobox/roles/alluxio-job-master/.env
        owner: vagrant
        group: vagrant

    - name: create alluxio conf directory
      file:
        dest: /home/vagrant/potatobox/conf/alluxio
        state: directory
        owner: vagrant
        group: vagrant

    - name: put alluxio-site.properties
      template:
        src: ../../conf/alluxio/alluxio-site.properties
        dest: /home/vagrant/potatobox/conf/alluxio/alluxio-site.properties
        owner: vagrant
        group: vagrant

    - name: restart alluxio-job-master
      shell:
        cmd: docker-compose --no-ansi exec job-master alluxio-stop.sh job-master; docker-compose --no-ansi kill; docker-compose --no-ansi up -d
        chdir: /home/vagrant/potatobox/roles/alluxio-job-master
